services:
  minio:
    image: minio/minio
    container_name: sws2apps-minio
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --address ":${MINIO_PORT}"
    volumes:
      - minio_data:/data

volumes:
  minio_data: